// Emoji autocomplete for the editor (`editor.emojiAutocomplete`). Typing a
// `:name` shortcode offers matching emojis; accepting one replaces the shortcode
// with the emoji character. A compact curated set of common shortcodes — not the
// full Unicode list — kept inline so there's no data dependency.

import type { CompletionContext, CompletionResult, Completion } from "@codemirror/autocomplete";

/**
 * `:shortcode` → emoji. Common, high-frequency entries. Shared with the live
 * preview: the parser validates a `:name:` against these keys and the renderer
 * looks up the glyph (see `emojiFor`), so autocomplete and rendering agree on
 * exactly which shortcodes are known.
 */
const EMOJI: Record<string, string> = {
  smile: "😄",
  smiley: "😃",
  grin: "😁",
  laughing: "😆",
  joy: "😂",
  rofl: "🤣",
  wink: "😉",
  blush: "😊",
  slight_smile: "🙂",
  upside_down: "🙃",
  heart_eyes: "😍",
  kissing_heart: "😘",
  yum: "😋",
  stuck_out_tongue: "😛",
  thinking: "🤔",
  neutral_face: "😐",
  expressionless: "😑",
  no_mouth: "😶",
  smirk: "😏",
  unamused: "😒",
  roll_eyes: "🙄",
  grimacing: "😬",
  relieved: "😌",
  pensive: "😔",
  sleepy: "😪",
  sleeping: "😴",
  mask: "😷",
  sunglasses: "😎",
  nerd: "🤓",
  confused: "😕",
  worried: "😟",
  frowning: "😦",
  anguished: "😧",
  cry: "😢",
  sob: "😭",
  weary: "😩",
  tired_face: "😫",
  triumph: "😤",
  angry: "😠",
  rage: "😡",
  exploding_head: "🤯",
  flushed: "😳",
  scream: "😱",
  fearful: "😨",
  cold_sweat: "😰",
  disappointed: "😞",
  sweat: "😓",
  party: "🥳",
  shush: "🤫",
  hugs: "🤗",
  thumbsup: "👍",
  "+1": "👍",
  thumbsdown: "👎",
  "-1": "👎",
  ok_hand: "👌",
  clap: "👏",
  wave: "👋",
  raised_hands: "🙌",
  pray: "🙏",
  muscle: "💪",
  point_up: "☝️",
  point_down: "👇",
  point_left: "👈",
  point_right: "👉",
  fire: "🔥",
  sparkles: "✨",
  star: "⭐",
  star2: "🌟",
  zap: "⚡",
  boom: "💥",
  tada: "🎉",
  confetti: "🎊",
  rocket: "🚀",
  bulb: "💡",
  warning: "⚠️",
  question: "❓",
  exclamation: "❗",
  check: "✅",
  white_check_mark: "✅",
  x: "❌",
  heavy_check_mark: "✔️",
  hourglass: "⏳",
  watch: "⌚",
  bell: "🔔",
  lock: "🔒",
  unlock: "🔓",
  key: "🔑",
  mag: "🔍",
  link: "🔗",
  pushpin: "📌",
  paperclip: "📎",
  memo: "📝",
  pencil: "✏️",
  book: "📖",
  books: "📚",
  bookmark: "🔖",
  calendar: "📅",
  clipboard: "📋",
  computer: "💻",
  keyboard: "⌨️",
  phone: "📱",
  email: "📧",
  inbox: "📥",
  outbox: "📤",
  package: "📦",
  gear: "⚙️",
  wrench: "🔧",
  hammer: "🔨",
  bug: "🐛",
  heart: "❤️",
  orange_heart: "🧡",
  yellow_heart: "💛",
  green_heart: "💚",
  blue_heart: "💙",
  purple_heart: "💜",
  broken_heart: "💔",
  sparkling_heart: "💖",
  100: "💯",
  eyes: "👀",
  brain: "🧠",
  coffee: "☕",
  beer: "🍺",
  pizza: "🍕",
  cake: "🍰",
  apple: "🍎",
  sun: "☀️",
  moon: "🌙",
  cloud: "☁️",
  rainbow: "🌈",
  snowflake: "❄️",
  dog: "🐶",
  cat: "🐱",
  unicorn: "🦄",
  penguin: "🐧",
  bird: "🐦",
  car: "🚗",
  airplane: "✈️",
  house: "🏠",
  office: "🏢",
  earth: "🌍",
  money: "💰",
  gem: "💎",
  gift: "🎁",
  trophy: "🏆",
  medal: "🏅",
  dart: "🎯",
  game: "🎮",
  music: "🎵",
  bomb: "💣",
  skull: "💀",
  ghost: "👻",
  alien: "👽",
  robot: "🤖",
  poop: "💩",
  wave_hand: "👋",
  ok: "🆗",
  new: "🆕",
  cool: "🆒",
  free: "🆓",
  up: "🔼",
  down: "🔽",
  arrow_right: "➡️",
  arrow_left: "⬅️",
  arrow_up: "⬆️",
  arrow_down: "⬇️",
  recycle: "♻️",
  infinity: "♾️",
};

const OPTIONS: Completion[] = Object.entries(EMOJI).map(([name, emoji]) => ({
  label: `:${name}:`,
  detail: emoji,
  type: "text",
  apply: emoji,
  boost: name.length <= 4 ? 1 : 0,
}));

/**
 * CodeMirror completion source: when the cursor follows a `:name` shortcode,
 * offer matching emojis. Requires at least one character after `:` so it doesn't
 * fire on a bare colon.
 */
export function emojiCompletions(context: CompletionContext): CompletionResult | null {
  const before = context.matchBefore(/:\w+/);
  if (!before) return null;
  const typed = before.text.slice(1).toLowerCase();
  if (!typed && !context.explicit) return null;
  const options = OPTIONS.filter((o) => o.label.slice(1, -1).startsWith(typed));
  if (!options.length) return null;
  return { from: before.from, to: context.pos, options, filter: false };
}

/**
 * Glyph for a `:name:` shortcode, or `undefined` if the name isn't a known
 * emoji. Used by the Markdown parser (to decide whether a `:name:` run is an
 * emoji) and the live-preview renderer (to fetch the glyph). Case-insensitive.
 */
export function emojiFor(name: string): string | undefined {
  return EMOJI[name.toLowerCase()];
}
